# just file name, no full path.
# include extensions

# example:
# rosservice call /publish_clouds "source_cloud_file: 'scan.pcd' target_cloud_file: 'cad.ply'"

string source_cloud_file
string target_cloud_file
---
bool success
string message
